# Generated by Django 5.1.15 on 2025-12-27 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='berita',
            options={'verbose_name_plural': 'Berita'},
        ),
        migrations.AlterModelOptions(
            name='dosen',
            options={'verbose_name_plural': 'Dosen'},
        ),
        migrations.AddField(
            model_name='dosen',
            name='nidn',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
