# Generated by Django 5.1.15 on 2025-12-27 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_berita_options_alter_dosen_options_dosen_nidn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosen',
            name='nidn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
